//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Pro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class abdullahaneesEntities : DbContext
    {
        public abdullahaneesEntities()
            : base("name=abdullahaneesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal void SaveChanges(registation registation)
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<registation> registations { get; set; }
    }
}
